export = Parallax;
declare class Parallax {
  constructor(element: any, options: any);
  element: any;
  inputElement: any;
  calibrationTimer: any;
  calibrationFlag: any;
  enabled: any;
  depthsX: any;
  depthsY: any;
  raf: any;
  bounds: any;
  elementPositionX: any;
  elementPositionY: any;
  elementWidth: any;
  elementHeight: any;
  elementCenterX: any;
  elementCenterY: any;
  elementRangeX: any;
  elementRangeY: any;
  calibrationX: any;
  calibrationY: any;
  inputX: any;
  inputY: any;
  motionX: any;
  motionY: any;
  velocityX: any;
  velocityY: any;
  onMouseMove(event: any): void;
  onDeviceOrientation(event: any): void;
  onDeviceMotion(event: any): void;
  onOrientationTimer(): void;
  onMotionTimer(): void;
  onCalibrationTimer(): void;
  onAnimationFrame(): void;
  onWindowResize(): void;
  windowWidth: any;
  windowHeight: any;
  windowCenterX: any;
  windowCenterY: any;
  windowRadiusX: any;
  windowRadiusY: any;
  portrait: any;
  desktop: any;
  motionSupport: any;
  orientationSupport: any;
  orientationStatus: any;
  motionStatus: any;
  calibrate(x: any, y: any): void;
  destroy(): void;
  disable(): void;
  doReadyCallback(): void;
  enable(): void;
  friction(x: any, y: any): void;
  initialise(): void;
  invert(x: any, y: any): void;
  limit(x: any, y: any): void;
  origin(x: any, y: any): void;
  queueCalibration(delay: any): void;
  rotate(beta: any, gamma: any): void;
  scalar(x: any, y: any): void;
  setInputElement(element: any): void;
  setPosition(element: any, x: any, y: any): void;
  updateBounds(): void;
  updateDimensions(): void;
  updateLayers(): void;
  version(): any;
}
